title: "ELEC 221 Course Notes"
author: "Your Name"
logo: "logo.png"
sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
execute:
  execute_notebooks: cache
